### PR TITLE
Following recent changes in Shopify/sarama.

### PR DESCRIPTION
**Pull request by avnik**
sarama split PartitionConsumer from Consumer, so I adopt these changes
here.

Please look on this changes, it should be useful.

### CODE REVIEW

**Comment by wvanbergen** [comment]
I addressed this in #29 as well.

**Comment by wvanbergen** [comment]
I think I prefer my approach, because it only opens 1 `sarama.Consumer` instance. This means that we will not open one connection per partition, but one connection per broker. Care to take a look at my PR?

**Comment by avnik** [comment]
I am ok with your way as well.
I just choose less-invasive path, to bypass compilation errors, and make stuff works.

Also want to ask, what you think about add convinience api for initialize producers via ZK? (seed them with .Brokers() for example)

**Comment by wvanbergen** [comment]
Yeah, a standalone helper function to initialize a `sarama.Client` based on zookeeper would be nice. This client can then be used to instantiate a `sarama.Producer` or `sarama.SimpleProducer`. 

Want to work on this? Most of it can be extracted from the `NewConsumerGroup` function.

**Comment by avnik** [comment]
At least I try to do that ;)
When you plan to merge #29?

**Comment by wvanbergen** [comment]
Probably today, just waiting on some code reviews.

**Comment by wvanbergen** [comment]
It's merged!

**Pull request closed without merging**
